name: PHPUnit tests with Symfony

inputs:
  php:
    description: PHP version to use
    required: true
  symfony:
    description: Symfony version to use
    required: true
    default: '*'
  deps:
    description: Dependency versions (highest/lowest)
    required: true
    default: highest
  phpunit:
    description: PHPUnit script (phpunit/simple-phpunit)
    required: true
    default: phpunit

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        coverage: none
        tools: flex

    - name: Install dependencies
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: ${{ inputs.deps }}
        composer-options: --prefer-dist
      env:
        SYMFONY_REQUIRE: ${{ inputs.symfony }}

    - name: Test
      run: vendor/bin/${{ inputs.phpunit }}
      shell: bash
