name: Code Coverage with Codecov
description: Run PHPUnit tests with code coverage and upload results to codecov.io

inputs:
  php:
    description: PHP Version to use
    default: '8.1'
    required: true
  phpunit:
    description: PHPUnit script (phpunit/simple-phpunit)
    required: true
    default: phpunit

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        coverage: xdebug
        ini-values: xdebug.mode=coverage

    - name: Install dependencies
      uses: ramsey/composer-install@v2
      with:
        composer-options: --prefer-dist

    - name: Test with coverage
      run: vendor/bin/${{ inputs.phpunit }} --coverage-text --coverage-clover coverage.xml
      shell: bash

    - name: Publish coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
