name: Test all supported PHP Versions

on:
  workflow_call:
    inputs:
      phpunit:
        description: PHPUnit script (phpunit/simple-phpunit)
        required: false
        default: phpunit
        type: string

jobs:
  test:
    name: PHP ${{ matrix.php }}, ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        deps: [highest]
        include:
          - php: 8.0
            deps: lowest
    steps:
      - uses: zenstruck/.github@php-test-symfony
        with:
          php: ${{ matrix.php }}
          deps: ${{ matrix.deps }}
          phpunit: ${{ inputs.phpunit }}
