name: Test all supported PHP/Symfony Versions

on:
  workflow_call:
    inputs:
      phpunit:
        description: PHPUnit script (phpunit/simple-phpunit)
        required: false
        default: phpunit
        type: string

jobs:
  test:
    name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0, 8.1, 8.2, 8.3]
        deps: [highest]
        symfony: [5.4.*, 6.3.*, 6.4.*, 7.0.*]
        include:
          - php: 8.0
            deps: lowest
            symfony: '*'
        exclude:
          - php: 8.0
            symfony: 6.3.*
          - php: 8.0
            symfony: 6.4.*
          - php: 8.0
            symfony: 7.0.*
          - php: 8.1
            symfony: 7.0.*
    steps:
      - uses: zenstruck/.github@php-test-symfony
        with:
          php: ${{ matrix.php }}
          symfony: ${{ matrix.symfony }}
          deps: ${{ matrix.deps }}
          phpunit: ${{ inputs.phpunit }}
